version: "3"
services:
  ridemapper:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: npm run dev
